CherrygroveCity_MapScripts::
	.byte 0


CherrygroveCity_BeachDude::
# 6 "data/maps/CherrygroveCity/scripts.pory"
	lock
# 7 "data/maps/CherrygroveCity/scripts.pory"
	faceplayer
# 8 "data/maps/CherrygroveCity/scripts.pory"
	msgbox CherrygroveCity_BeachDude_Text_0
# 9 "data/maps/CherrygroveCity/scripts.pory"
	release
	return


CherrygroveCity_Woman::
# 13 "data/maps/CherrygroveCity/scripts.pory"
	lock
# 14 "data/maps/CherrygroveCity/scripts.pory"
	faceplayer
# 15 "data/maps/CherrygroveCity/scripts.pory"
	msgbox CherrygroveCity_Woman_Text_0
# 16 "data/maps/CherrygroveCity/scripts.pory"
	release
	return


CherrygroveCity_Youngster::
# 20 "data/maps/CherrygroveCity/scripts.pory"
	lock
# 21 "data/maps/CherrygroveCity/scripts.pory"
	faceplayer
# 22 "data/maps/CherrygroveCity/scripts.pory"
	msgbox CherrygroveCity_Youngster_Text_0
# 23 "data/maps/CherrygroveCity/scripts.pory"
	release
	return


CherrygroveCity_Guide::
# 27 "data/maps/CherrygroveCity/scripts.pory"
	lock
# 28 "data/maps/CherrygroveCity/scripts.pory"
	faceplayer
# 29 "data/maps/CherrygroveCity/scripts.pory"
	msgbox CherrygroveCity_Guide_Text_0
# 30 "data/maps/CherrygroveCity/scripts.pory"
	release
	return


CherrygroveCity_CitySign::
# 34 "data/maps/CherrygroveCity/scripts.pory"
	lock
# 35 "data/maps/CherrygroveCity/scripts.pory"
	msgbox CherrygroveCity_CitySign_Text_0
# 36 "data/maps/CherrygroveCity/scripts.pory"
	release
	return


CherrygroveCity_GuideGentSign::
# 40 "data/maps/CherrygroveCity/scripts.pory"
	lock
# 41 "data/maps/CherrygroveCity/scripts.pory"
	msgbox CherrygroveCity_GuideGentSign_Text_0
# 42 "data/maps/CherrygroveCity/scripts.pory"
	release
	return


CherrygroveCity_GuideGentSign::
# 46 "data/maps/CherrygroveCity/scripts.pory"
	lock
# 47 "data/maps/CherrygroveCity/scripts.pory"
	msgbox CherrygroveCity_GuideGentSign_Text_1
# 48 "data/maps/CherrygroveCity/scripts.pory"
	release
	return


CherrygroveCity_BeachDude_Text_0:
# 8 "data/maps/CherrygroveCity/scripts.pory"
	.string "I love hanging out on the beach of\n"
	.string "CHERRYGROVE BAY!\p"
	.string "You can see ROUTE 32 from here when the\n"
	.string "weather's good.$"

CherrygroveCity_Woman_Text_0:
# 15 "data/maps/CherrygroveCity/scripts.pory"
	.string "I love going for a stroll through the\n"
	.string "cherry trees with my boyfriend.\p"
	.string "You're doing it with your POKéMON.\p"
	.string "I wonder which is better?$"

CherrygroveCity_Youngster_Text_0:
# 22 "data/maps/CherrygroveCity/scripts.pory"
	.string "I don't think that FURRET is supposed\n"
	.string "to be walking on the flowers.\p"
	.string "At least my mom told me I wasn't\n"
	.string "supposed to do it yesterday.\p"
	.string "Life must be great as a POKéMON...$"

CherrygroveCity_Guide_Text_0:
# 29 "data/maps/CherrygroveCity/scripts.pory"
	.string "I'm an old man who will guide.$"

CherrygroveCity_CitySign_Text_0:
# 35 "data/maps/CherrygroveCity/scripts.pory"
	.string "CHERRYGROVE CITY\p"
	.string "The City of Cute, Fragrant Flowers$"

CherrygroveCity_GuideGentSign_Text_0:
# 41 "data/maps/CherrygroveCity/scripts.pory"
	.string "GUIDE GENT'S HOUSE$"

CherrygroveCity_GuideGentSign_Text_1:
# 47 "data/maps/CherrygroveCity/scripts.pory"
	.string "BLOOMING BLOSSOM'S FLOWER SHOPPE$"
