NewBarkTown_NPCHouse_MapScripts::
	.byte 0


NewBarkTown_NPCHouse_ElmFangirl::
# 11 "data/maps/NewBarkTown_NPCHouse/scripts.pory"
	lock
# 12 "data/maps/NewBarkTown_NPCHouse/scripts.pory"
	faceplayer
# 13 "data/maps/NewBarkTown_NPCHouse/scripts.pory"
	msgbox NewBarkTown_NPCHouse_ElmFangirl_Text_0
# 14 "data/maps/NewBarkTown_NPCHouse/scripts.pory"
	release
	return


NewBarkTown_NPCHouse_ElmFangirl_Text_0:
# 13 "data/maps/NewBarkTown_NPCHouse/scripts.pory"
	.string "It turns out PIKACHU is an evolved\n"
	.string "POKéMON!\p"
	.string "I was amazed by PROF. ELM's findings.\p"
	.string "He's so famous for his research on\n"
	.string "POKéMON breeding and evolution.\p"
	.string "...sigh...\p"
	.string "I wish I could be a researcher like he\n"
	.string "is. Or even his assistant!$"
